# This config sets up a simple, single-node cluster that's equipped to use SASL.
# See examples/tls for the associated cluster configs and certs.
#
# To verify that TLS is working properly, try something like:
#
# openssl s_client -debug -connect localhost:9093 -CAfile ca.crt \
#   -cert server.crt -key server.key
version: '2'

services:
  zookeeper:
    image: "wurstmeister/zookeeper:latest"
    ports:
      - "2181:2181"

  kafka1:
    image: wurstmeister/kafka:2.12-2.4.1
    ports:
      - "9094:9094"
      - "9095:9095"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_BROKER_RACK: zone1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9094,SASL_SSL://:9095
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://127.0.0.1:9094,SASL_SSL://127.0.0.1:9095
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_SSL_KEYSTORE_LOCATION: "/certs/kafka.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "test123"
      KAFKA_SSL_KEY_PASSWORD: "test123"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/certs/kafka.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "test123"
      KAFKA_SSL_CLIENT_AUTH: "none"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: "SSL"
      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN,SCRAM-SHA-256,SCRAM-SHA-512"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/config/kafka_server_jaas.conf"
      CUSTOM_INIT_SCRIPT: |-
        echo -e 'KafkaServer {\norg.apache.kafka.common.security.scram.ScramLoginModule required\n username="adminscram"\n password="admin-secret";\n org.apache.kafka.common.security.plain.PlainLoginModule required\n username="adminplain"\n password="admin-secret"\n user_adminplain="admin-secret";\n  };' > /opt/kafka/config/kafka_server_jaas.conf;
        /opt/kafka/bin/kafka-configs.sh --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=admin-secret-256],SCRAM-SHA-512=[password=admin-secret-512]' --entity-type users --entity-name adminscram
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./examples/auth/certs:/certs
