name: dockerhub-publish

#on:
#  push:
#    tags: 
#     - /v[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9-]+)?/
#  pull_request:
#    tags: 
#     - /v[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9-]+)?/

on:
  push:
    branches: [ "master", "v0", "DP-556-migrate-topicctl-to-github-actions" ]
  pull_request:
    branches: [ "master", "v0", "DP-556-migrate-topicctl-to-github-actions" ]

jobs:
  test010:
    uses: 
      ./.github/workflows/test010.yml
  test241:
    uses: 
      ./.github/workflows/test241.yml
  publish-dockerhub:
    runs-on: ubuntu-latest
    needs: [test010, test241]
    steps:
    - uses: actions/checkout@v3
    - name: setup env variables
      id: vars
      run: |
        echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Print tag
      run: echo $RELEASE_TAG
    - name: Build and push image
      run:  |
            docker login -u $DOCKER_USER -p $DOCKER_PASS

            docker context create buildx-build
            docker buildx create --use buildx-build
            docker buildx build \
              --platform=linux/amd64,linux/arm64 \
              -t segment/topicctl:${RELEASE_TAG} \
              -t segment/topicctl:latest \
              --build-arg VERSION=${RELEASE_TAG} \
              --push \
              .
