name: ghcr-publish

on:
  push:
    branches: [ "DP-556-migrate-topicctl-to-github-actions" ]
  pull_request:
    branches: [ "DP-556-migrate-topicctl-to-github-actions" ]

jobs:
  tests:
    uses: 
      ./.github/workflows/test010.yml
      ./.github/workflows/test241.yml
  publish-ghcr:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
    - uses: actions/checkout@v3
    - name: setup env variables
      id: vars
      run: |
        echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - name: Log in to the Container registry
      uses: docker/login-action@v2.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push image
      run:  |
        docker context create buildx-build
        docker buildx create --use buildx-build
        docker buildx build \
          -t ghcr.io/segment/topicctl:${SHORT_SHA} \
          --build-arg VERSION=${SHORT_SHA} \
          --push \
          .
