name: ghcr-publish

on:
  push:
    branches: [ "master", "v0", "DP-556-migrate-topicctl-to-github-actions" ]
  pull_request:
    branches: [ "master", "v0", "DP-556-migrate-topicctl-to-github-actions" ]

jobs:
  test010:
    uses: 
      ./.github/workflows/test010.yml
  test241:
    uses: 
      ./.github/workflows/test241.yml
  publish-ghcr:
    runs-on: ubuntu-latest
    needs: [test010, test241]
    steps:
    - uses: actions/checkout@v3
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/golang@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --fail-on=upgradable
    - name: setup env variables
      id: vars
      run: |
        echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: true
    - name: Build and push image
      run:  |
        docker context create buildx-build
        docker buildx create --use buildx-build
        docker buildx build \
          -t ghcr.io/segmentio/topicctl:${SHORT_SHA} \
          --build-arg VERSION=${SHORT_SHA} \
          --push \
          .
